version: '3.3'

services:

  web:
    build: /home/evgeny/PycharmProjects/ScraperCian
    restart: always
    command: core.wsgi:application --bind 0.0.0.0:8000 --reload
    environment:
      - TZ=Europe/Moscow
      - DEBUG=1
    ports:
      - 8000:8000
    env_file:
      - .env

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - web
    ports:
      - "80:80"