version: '3.3'

services:

  web:
    build: .

    environment:
      - TZ=Europe/Moscow
    ports:
      - 8000:8000
    env_file:
      - .env

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - web
    ports:
      - 80:80
    volumes:
      - ./static/:/static
      - ./media/:/media
